/*
Strava API v3

The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package strava

import (
	"encoding/json"
)

// StreamSet struct for StreamSet
type StreamSet struct {
	Time *TimeStream `json:"time,omitempty"`
	Distance *DistanceStream `json:"distance,omitempty"`
	Latlng *LatLngStream `json:"latlng,omitempty"`
	Altitude *AltitudeStream `json:"altitude,omitempty"`
	VelocitySmooth *SmoothVelocityStream `json:"velocity_smooth,omitempty"`
	Heartrate *HeartrateStream `json:"heartrate,omitempty"`
	Cadence *CadenceStream `json:"cadence,omitempty"`
	Watts *PowerStream `json:"watts,omitempty"`
	Temp *TemperatureStream `json:"temp,omitempty"`
	Moving *MovingStream `json:"moving,omitempty"`
	GradeSmooth *SmoothGradeStream `json:"grade_smooth,omitempty"`
}

// NewStreamSet instantiates a new StreamSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamSet() *StreamSet {
	this := StreamSet{}
	return &this
}

// NewStreamSetWithDefaults instantiates a new StreamSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamSetWithDefaults() *StreamSet {
	this := StreamSet{}
	return &this
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *StreamSet) GetTime() TimeStream {
	if o == nil || o.Time == nil {
		var ret TimeStream
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetTimeOk() (*TimeStream, bool) {
	if o == nil || o.Time == nil {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *StreamSet) HasTime() bool {
	if o != nil && o.Time != nil {
		return true
	}

	return false
}

// SetTime gets a reference to the given TimeStream and assigns it to the Time field.
func (o *StreamSet) SetTime(v TimeStream) {
	o.Time = &v
}

// GetDistance returns the Distance field value if set, zero value otherwise.
func (o *StreamSet) GetDistance() DistanceStream {
	if o == nil || o.Distance == nil {
		var ret DistanceStream
		return ret
	}
	return *o.Distance
}

// GetDistanceOk returns a tuple with the Distance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetDistanceOk() (*DistanceStream, bool) {
	if o == nil || o.Distance == nil {
		return nil, false
	}
	return o.Distance, true
}

// HasDistance returns a boolean if a field has been set.
func (o *StreamSet) HasDistance() bool {
	if o != nil && o.Distance != nil {
		return true
	}

	return false
}

// SetDistance gets a reference to the given DistanceStream and assigns it to the Distance field.
func (o *StreamSet) SetDistance(v DistanceStream) {
	o.Distance = &v
}

// GetLatlng returns the Latlng field value if set, zero value otherwise.
func (o *StreamSet) GetLatlng() LatLngStream {
	if o == nil || o.Latlng == nil {
		var ret LatLngStream
		return ret
	}
	return *o.Latlng
}

// GetLatlngOk returns a tuple with the Latlng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetLatlngOk() (*LatLngStream, bool) {
	if o == nil || o.Latlng == nil {
		return nil, false
	}
	return o.Latlng, true
}

// HasLatlng returns a boolean if a field has been set.
func (o *StreamSet) HasLatlng() bool {
	if o != nil && o.Latlng != nil {
		return true
	}

	return false
}

// SetLatlng gets a reference to the given LatLngStream and assigns it to the Latlng field.
func (o *StreamSet) SetLatlng(v LatLngStream) {
	o.Latlng = &v
}

// GetAltitude returns the Altitude field value if set, zero value otherwise.
func (o *StreamSet) GetAltitude() AltitudeStream {
	if o == nil || o.Altitude == nil {
		var ret AltitudeStream
		return ret
	}
	return *o.Altitude
}

// GetAltitudeOk returns a tuple with the Altitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetAltitudeOk() (*AltitudeStream, bool) {
	if o == nil || o.Altitude == nil {
		return nil, false
	}
	return o.Altitude, true
}

// HasAltitude returns a boolean if a field has been set.
func (o *StreamSet) HasAltitude() bool {
	if o != nil && o.Altitude != nil {
		return true
	}

	return false
}

// SetAltitude gets a reference to the given AltitudeStream and assigns it to the Altitude field.
func (o *StreamSet) SetAltitude(v AltitudeStream) {
	o.Altitude = &v
}

// GetVelocitySmooth returns the VelocitySmooth field value if set, zero value otherwise.
func (o *StreamSet) GetVelocitySmooth() SmoothVelocityStream {
	if o == nil || o.VelocitySmooth == nil {
		var ret SmoothVelocityStream
		return ret
	}
	return *o.VelocitySmooth
}

// GetVelocitySmoothOk returns a tuple with the VelocitySmooth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetVelocitySmoothOk() (*SmoothVelocityStream, bool) {
	if o == nil || o.VelocitySmooth == nil {
		return nil, false
	}
	return o.VelocitySmooth, true
}

// HasVelocitySmooth returns a boolean if a field has been set.
func (o *StreamSet) HasVelocitySmooth() bool {
	if o != nil && o.VelocitySmooth != nil {
		return true
	}

	return false
}

// SetVelocitySmooth gets a reference to the given SmoothVelocityStream and assigns it to the VelocitySmooth field.
func (o *StreamSet) SetVelocitySmooth(v SmoothVelocityStream) {
	o.VelocitySmooth = &v
}

// GetHeartrate returns the Heartrate field value if set, zero value otherwise.
func (o *StreamSet) GetHeartrate() HeartrateStream {
	if o == nil || o.Heartrate == nil {
		var ret HeartrateStream
		return ret
	}
	return *o.Heartrate
}

// GetHeartrateOk returns a tuple with the Heartrate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetHeartrateOk() (*HeartrateStream, bool) {
	if o == nil || o.Heartrate == nil {
		return nil, false
	}
	return o.Heartrate, true
}

// HasHeartrate returns a boolean if a field has been set.
func (o *StreamSet) HasHeartrate() bool {
	if o != nil && o.Heartrate != nil {
		return true
	}

	return false
}

// SetHeartrate gets a reference to the given HeartrateStream and assigns it to the Heartrate field.
func (o *StreamSet) SetHeartrate(v HeartrateStream) {
	o.Heartrate = &v
}

// GetCadence returns the Cadence field value if set, zero value otherwise.
func (o *StreamSet) GetCadence() CadenceStream {
	if o == nil || o.Cadence == nil {
		var ret CadenceStream
		return ret
	}
	return *o.Cadence
}

// GetCadenceOk returns a tuple with the Cadence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetCadenceOk() (*CadenceStream, bool) {
	if o == nil || o.Cadence == nil {
		return nil, false
	}
	return o.Cadence, true
}

// HasCadence returns a boolean if a field has been set.
func (o *StreamSet) HasCadence() bool {
	if o != nil && o.Cadence != nil {
		return true
	}

	return false
}

// SetCadence gets a reference to the given CadenceStream and assigns it to the Cadence field.
func (o *StreamSet) SetCadence(v CadenceStream) {
	o.Cadence = &v
}

// GetWatts returns the Watts field value if set, zero value otherwise.
func (o *StreamSet) GetWatts() PowerStream {
	if o == nil || o.Watts == nil {
		var ret PowerStream
		return ret
	}
	return *o.Watts
}

// GetWattsOk returns a tuple with the Watts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetWattsOk() (*PowerStream, bool) {
	if o == nil || o.Watts == nil {
		return nil, false
	}
	return o.Watts, true
}

// HasWatts returns a boolean if a field has been set.
func (o *StreamSet) HasWatts() bool {
	if o != nil && o.Watts != nil {
		return true
	}

	return false
}

// SetWatts gets a reference to the given PowerStream and assigns it to the Watts field.
func (o *StreamSet) SetWatts(v PowerStream) {
	o.Watts = &v
}

// GetTemp returns the Temp field value if set, zero value otherwise.
func (o *StreamSet) GetTemp() TemperatureStream {
	if o == nil || o.Temp == nil {
		var ret TemperatureStream
		return ret
	}
	return *o.Temp
}

// GetTempOk returns a tuple with the Temp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetTempOk() (*TemperatureStream, bool) {
	if o == nil || o.Temp == nil {
		return nil, false
	}
	return o.Temp, true
}

// HasTemp returns a boolean if a field has been set.
func (o *StreamSet) HasTemp() bool {
	if o != nil && o.Temp != nil {
		return true
	}

	return false
}

// SetTemp gets a reference to the given TemperatureStream and assigns it to the Temp field.
func (o *StreamSet) SetTemp(v TemperatureStream) {
	o.Temp = &v
}

// GetMoving returns the Moving field value if set, zero value otherwise.
func (o *StreamSet) GetMoving() MovingStream {
	if o == nil || o.Moving == nil {
		var ret MovingStream
		return ret
	}
	return *o.Moving
}

// GetMovingOk returns a tuple with the Moving field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetMovingOk() (*MovingStream, bool) {
	if o == nil || o.Moving == nil {
		return nil, false
	}
	return o.Moving, true
}

// HasMoving returns a boolean if a field has been set.
func (o *StreamSet) HasMoving() bool {
	if o != nil && o.Moving != nil {
		return true
	}

	return false
}

// SetMoving gets a reference to the given MovingStream and assigns it to the Moving field.
func (o *StreamSet) SetMoving(v MovingStream) {
	o.Moving = &v
}

// GetGradeSmooth returns the GradeSmooth field value if set, zero value otherwise.
func (o *StreamSet) GetGradeSmooth() SmoothGradeStream {
	if o == nil || o.GradeSmooth == nil {
		var ret SmoothGradeStream
		return ret
	}
	return *o.GradeSmooth
}

// GetGradeSmoothOk returns a tuple with the GradeSmooth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamSet) GetGradeSmoothOk() (*SmoothGradeStream, bool) {
	if o == nil || o.GradeSmooth == nil {
		return nil, false
	}
	return o.GradeSmooth, true
}

// HasGradeSmooth returns a boolean if a field has been set.
func (o *StreamSet) HasGradeSmooth() bool {
	if o != nil && o.GradeSmooth != nil {
		return true
	}

	return false
}

// SetGradeSmooth gets a reference to the given SmoothGradeStream and assigns it to the GradeSmooth field.
func (o *StreamSet) SetGradeSmooth(v SmoothGradeStream) {
	o.GradeSmooth = &v
}

func (o StreamSet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Time != nil {
		toSerialize["time"] = o.Time
	}
	if o.Distance != nil {
		toSerialize["distance"] = o.Distance
	}
	if o.Latlng != nil {
		toSerialize["latlng"] = o.Latlng
	}
	if o.Altitude != nil {
		toSerialize["altitude"] = o.Altitude
	}
	if o.VelocitySmooth != nil {
		toSerialize["velocity_smooth"] = o.VelocitySmooth
	}
	if o.Heartrate != nil {
		toSerialize["heartrate"] = o.Heartrate
	}
	if o.Cadence != nil {
		toSerialize["cadence"] = o.Cadence
	}
	if o.Watts != nil {
		toSerialize["watts"] = o.Watts
	}
	if o.Temp != nil {
		toSerialize["temp"] = o.Temp
	}
	if o.Moving != nil {
		toSerialize["moving"] = o.Moving
	}
	if o.GradeSmooth != nil {
		toSerialize["grade_smooth"] = o.GradeSmooth
	}
	return json.Marshal(toSerialize)
}

type NullableStreamSet struct {
	value *StreamSet
	isSet bool
}

func (v NullableStreamSet) Get() *StreamSet {
	return v.value
}

func (v *NullableStreamSet) Set(val *StreamSet) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamSet) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamSet(val *StreamSet) *NullableStreamSet {
	return &NullableStreamSet{value: val, isSet: true}
}

func (v NullableStreamSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


