/*
Strava API v3

The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package strava

import (
	"encoding/json"
	"time"
)

// SummaryActivityAllOf struct for SummaryActivityAllOf
type SummaryActivityAllOf struct {
	// The identifier provided at upload time
	ExternalId *string `json:"external_id,omitempty"`
	// The identifier of the upload that resulted in this activity
	UploadId *int64 `json:"upload_id,omitempty"`
	Athlete *MetaAthlete `json:"athlete,omitempty"`
	// The name of the activity
	Name *string `json:"name,omitempty"`
	// The activity's distance, in meters
	Distance *float32 `json:"distance,omitempty"`
	// The activity's moving time, in seconds
	MovingTime *int32 `json:"moving_time,omitempty"`
	// The activity's elapsed time, in seconds
	ElapsedTime *int32 `json:"elapsed_time,omitempty"`
	// The activity's total elevation gain.
	TotalElevationGain *float32 `json:"total_elevation_gain,omitempty"`
	// The activity's highest elevation, in meters
	ElevHigh *float32 `json:"elev_high,omitempty"`
	// The activity's lowest elevation, in meters
	ElevLow *float32 `json:"elev_low,omitempty"`
	Type *ActivityType `json:"type,omitempty"`
	SportType *SportType `json:"sport_type,omitempty"`
	// The time at which the activity was started.
	StartDate *time.Time `json:"start_date,omitempty"`
	// The time at which the activity was started in the local timezone.
	StartDateLocal *time.Time `json:"start_date_local,omitempty"`
	// The timezone of the activity
	Timezone *string `json:"timezone,omitempty"`
	// A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
	StartLatlng []float32 `json:"start_latlng,omitempty"`
	// A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.
	EndLatlng []float32 `json:"end_latlng,omitempty"`
	// The number of achievements gained during this activity
	AchievementCount *int32 `json:"achievement_count,omitempty"`
	// The number of kudos given for this activity
	KudosCount *int32 `json:"kudos_count,omitempty"`
	// The number of comments for this activity
	CommentCount *int32 `json:"comment_count,omitempty"`
	// The number of athletes for taking part in a group activity
	AthleteCount *int32 `json:"athlete_count,omitempty"`
	// The number of Instagram photos for this activity
	PhotoCount *int32 `json:"photo_count,omitempty"`
	// The number of Instagram and Strava photos for this activity
	TotalPhotoCount *int32 `json:"total_photo_count,omitempty"`
	Map *PolylineMap `json:"map,omitempty"`
	// Whether this activity was recorded on a training machine
	Trainer *bool `json:"trainer,omitempty"`
	// Whether this activity is a commute
	Commute *bool `json:"commute,omitempty"`
	// Whether this activity was created manually
	Manual *bool `json:"manual,omitempty"`
	// Whether this activity is private
	Private *bool `json:"private,omitempty"`
	// Whether this activity is flagged
	Flagged *bool `json:"flagged,omitempty"`
	// The activity's workout type
	WorkoutType *int32 `json:"workout_type,omitempty"`
	// The unique identifier of the upload in string format
	UploadIdStr *string `json:"upload_id_str,omitempty"`
	// The activity's average speed, in meters per second
	AverageSpeed *float32 `json:"average_speed,omitempty"`
	// The activity's max speed, in meters per second
	MaxSpeed *float32 `json:"max_speed,omitempty"`
	// Whether the logged-in athlete has kudoed this activity
	HasKudoed *bool `json:"has_kudoed,omitempty"`
	// Whether the activity is muted
	HideFromHome *bool `json:"hide_from_home,omitempty"`
	// The id of the gear for the activity
	GearId *string `json:"gear_id,omitempty"`
	// The total work done in kilojoules during this activity. Rides only
	Kilojoules *float32 `json:"kilojoules,omitempty"`
	// Average power output in watts during this activity. Rides only
	AverageWatts *float32 `json:"average_watts,omitempty"`
	// Whether the watts are from a power meter, false if estimated
	DeviceWatts *bool `json:"device_watts,omitempty"`
	// Rides with power meter data only
	MaxWatts *int32 `json:"max_watts,omitempty"`
	// Similar to Normalized Power. Rides with power meter data only
	WeightedAverageWatts *int32 `json:"weighted_average_watts,omitempty"`
}

// NewSummaryActivityAllOf instantiates a new SummaryActivityAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummaryActivityAllOf() *SummaryActivityAllOf {
	this := SummaryActivityAllOf{}
	return &this
}

// NewSummaryActivityAllOfWithDefaults instantiates a new SummaryActivityAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryActivityAllOfWithDefaults() *SummaryActivityAllOf {
	this := SummaryActivityAllOf{}
	return &this
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetExternalId() string {
	if o == nil || o.ExternalId == nil {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetExternalIdOk() (*string, bool) {
	if o == nil || o.ExternalId == nil {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasExternalId() bool {
	if o != nil && o.ExternalId != nil {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *SummaryActivityAllOf) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetUploadId returns the UploadId field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetUploadId() int64 {
	if o == nil || o.UploadId == nil {
		var ret int64
		return ret
	}
	return *o.UploadId
}

// GetUploadIdOk returns a tuple with the UploadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetUploadIdOk() (*int64, bool) {
	if o == nil || o.UploadId == nil {
		return nil, false
	}
	return o.UploadId, true
}

// HasUploadId returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasUploadId() bool {
	if o != nil && o.UploadId != nil {
		return true
	}

	return false
}

// SetUploadId gets a reference to the given int64 and assigns it to the UploadId field.
func (o *SummaryActivityAllOf) SetUploadId(v int64) {
	o.UploadId = &v
}

// GetAthlete returns the Athlete field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetAthlete() MetaAthlete {
	if o == nil || o.Athlete == nil {
		var ret MetaAthlete
		return ret
	}
	return *o.Athlete
}

// GetAthleteOk returns a tuple with the Athlete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetAthleteOk() (*MetaAthlete, bool) {
	if o == nil || o.Athlete == nil {
		return nil, false
	}
	return o.Athlete, true
}

// HasAthlete returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasAthlete() bool {
	if o != nil && o.Athlete != nil {
		return true
	}

	return false
}

// SetAthlete gets a reference to the given MetaAthlete and assigns it to the Athlete field.
func (o *SummaryActivityAllOf) SetAthlete(v MetaAthlete) {
	o.Athlete = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SummaryActivityAllOf) SetName(v string) {
	o.Name = &v
}

// GetDistance returns the Distance field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetDistance() float32 {
	if o == nil || o.Distance == nil {
		var ret float32
		return ret
	}
	return *o.Distance
}

// GetDistanceOk returns a tuple with the Distance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetDistanceOk() (*float32, bool) {
	if o == nil || o.Distance == nil {
		return nil, false
	}
	return o.Distance, true
}

// HasDistance returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasDistance() bool {
	if o != nil && o.Distance != nil {
		return true
	}

	return false
}

// SetDistance gets a reference to the given float32 and assigns it to the Distance field.
func (o *SummaryActivityAllOf) SetDistance(v float32) {
	o.Distance = &v
}

// GetMovingTime returns the MovingTime field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetMovingTime() int32 {
	if o == nil || o.MovingTime == nil {
		var ret int32
		return ret
	}
	return *o.MovingTime
}

// GetMovingTimeOk returns a tuple with the MovingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetMovingTimeOk() (*int32, bool) {
	if o == nil || o.MovingTime == nil {
		return nil, false
	}
	return o.MovingTime, true
}

// HasMovingTime returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasMovingTime() bool {
	if o != nil && o.MovingTime != nil {
		return true
	}

	return false
}

// SetMovingTime gets a reference to the given int32 and assigns it to the MovingTime field.
func (o *SummaryActivityAllOf) SetMovingTime(v int32) {
	o.MovingTime = &v
}

// GetElapsedTime returns the ElapsedTime field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetElapsedTime() int32 {
	if o == nil || o.ElapsedTime == nil {
		var ret int32
		return ret
	}
	return *o.ElapsedTime
}

// GetElapsedTimeOk returns a tuple with the ElapsedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetElapsedTimeOk() (*int32, bool) {
	if o == nil || o.ElapsedTime == nil {
		return nil, false
	}
	return o.ElapsedTime, true
}

// HasElapsedTime returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasElapsedTime() bool {
	if o != nil && o.ElapsedTime != nil {
		return true
	}

	return false
}

// SetElapsedTime gets a reference to the given int32 and assigns it to the ElapsedTime field.
func (o *SummaryActivityAllOf) SetElapsedTime(v int32) {
	o.ElapsedTime = &v
}

// GetTotalElevationGain returns the TotalElevationGain field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetTotalElevationGain() float32 {
	if o == nil || o.TotalElevationGain == nil {
		var ret float32
		return ret
	}
	return *o.TotalElevationGain
}

// GetTotalElevationGainOk returns a tuple with the TotalElevationGain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetTotalElevationGainOk() (*float32, bool) {
	if o == nil || o.TotalElevationGain == nil {
		return nil, false
	}
	return o.TotalElevationGain, true
}

// HasTotalElevationGain returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasTotalElevationGain() bool {
	if o != nil && o.TotalElevationGain != nil {
		return true
	}

	return false
}

// SetTotalElevationGain gets a reference to the given float32 and assigns it to the TotalElevationGain field.
func (o *SummaryActivityAllOf) SetTotalElevationGain(v float32) {
	o.TotalElevationGain = &v
}

// GetElevHigh returns the ElevHigh field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetElevHigh() float32 {
	if o == nil || o.ElevHigh == nil {
		var ret float32
		return ret
	}
	return *o.ElevHigh
}

// GetElevHighOk returns a tuple with the ElevHigh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetElevHighOk() (*float32, bool) {
	if o == nil || o.ElevHigh == nil {
		return nil, false
	}
	return o.ElevHigh, true
}

// HasElevHigh returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasElevHigh() bool {
	if o != nil && o.ElevHigh != nil {
		return true
	}

	return false
}

// SetElevHigh gets a reference to the given float32 and assigns it to the ElevHigh field.
func (o *SummaryActivityAllOf) SetElevHigh(v float32) {
	o.ElevHigh = &v
}

// GetElevLow returns the ElevLow field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetElevLow() float32 {
	if o == nil || o.ElevLow == nil {
		var ret float32
		return ret
	}
	return *o.ElevLow
}

// GetElevLowOk returns a tuple with the ElevLow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetElevLowOk() (*float32, bool) {
	if o == nil || o.ElevLow == nil {
		return nil, false
	}
	return o.ElevLow, true
}

// HasElevLow returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasElevLow() bool {
	if o != nil && o.ElevLow != nil {
		return true
	}

	return false
}

// SetElevLow gets a reference to the given float32 and assigns it to the ElevLow field.
func (o *SummaryActivityAllOf) SetElevLow(v float32) {
	o.ElevLow = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetType() ActivityType {
	if o == nil || o.Type == nil {
		var ret ActivityType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetTypeOk() (*ActivityType, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given ActivityType and assigns it to the Type field.
func (o *SummaryActivityAllOf) SetType(v ActivityType) {
	o.Type = &v
}

// GetSportType returns the SportType field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetSportType() SportType {
	if o == nil || o.SportType == nil {
		var ret SportType
		return ret
	}
	return *o.SportType
}

// GetSportTypeOk returns a tuple with the SportType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetSportTypeOk() (*SportType, bool) {
	if o == nil || o.SportType == nil {
		return nil, false
	}
	return o.SportType, true
}

// HasSportType returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasSportType() bool {
	if o != nil && o.SportType != nil {
		return true
	}

	return false
}

// SetSportType gets a reference to the given SportType and assigns it to the SportType field.
func (o *SummaryActivityAllOf) SetSportType(v SportType) {
	o.SportType = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetStartDate() time.Time {
	if o == nil || o.StartDate == nil {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetStartDateOk() (*time.Time, bool) {
	if o == nil || o.StartDate == nil {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasStartDate() bool {
	if o != nil && o.StartDate != nil {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *SummaryActivityAllOf) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetStartDateLocal returns the StartDateLocal field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetStartDateLocal() time.Time {
	if o == nil || o.StartDateLocal == nil {
		var ret time.Time
		return ret
	}
	return *o.StartDateLocal
}

// GetStartDateLocalOk returns a tuple with the StartDateLocal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetStartDateLocalOk() (*time.Time, bool) {
	if o == nil || o.StartDateLocal == nil {
		return nil, false
	}
	return o.StartDateLocal, true
}

// HasStartDateLocal returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasStartDateLocal() bool {
	if o != nil && o.StartDateLocal != nil {
		return true
	}

	return false
}

// SetStartDateLocal gets a reference to the given time.Time and assigns it to the StartDateLocal field.
func (o *SummaryActivityAllOf) SetStartDateLocal(v time.Time) {
	o.StartDateLocal = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetTimezone() string {
	if o == nil || o.Timezone == nil {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetTimezoneOk() (*string, bool) {
	if o == nil || o.Timezone == nil {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasTimezone() bool {
	if o != nil && o.Timezone != nil {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *SummaryActivityAllOf) SetTimezone(v string) {
	o.Timezone = &v
}

// GetStartLatlng returns the StartLatlng field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetStartLatlng() []float32 {
	if o == nil || o.StartLatlng == nil {
		var ret []float32
		return ret
	}
	return o.StartLatlng
}

// GetStartLatlngOk returns a tuple with the StartLatlng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetStartLatlngOk() ([]float32, bool) {
	if o == nil || o.StartLatlng == nil {
		return nil, false
	}
	return o.StartLatlng, true
}

// HasStartLatlng returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasStartLatlng() bool {
	if o != nil && o.StartLatlng != nil {
		return true
	}

	return false
}

// SetStartLatlng gets a reference to the given []float32 and assigns it to the StartLatlng field.
func (o *SummaryActivityAllOf) SetStartLatlng(v []float32) {
	o.StartLatlng = v
}

// GetEndLatlng returns the EndLatlng field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetEndLatlng() []float32 {
	if o == nil || o.EndLatlng == nil {
		var ret []float32
		return ret
	}
	return o.EndLatlng
}

// GetEndLatlngOk returns a tuple with the EndLatlng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetEndLatlngOk() ([]float32, bool) {
	if o == nil || o.EndLatlng == nil {
		return nil, false
	}
	return o.EndLatlng, true
}

// HasEndLatlng returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasEndLatlng() bool {
	if o != nil && o.EndLatlng != nil {
		return true
	}

	return false
}

// SetEndLatlng gets a reference to the given []float32 and assigns it to the EndLatlng field.
func (o *SummaryActivityAllOf) SetEndLatlng(v []float32) {
	o.EndLatlng = v
}

// GetAchievementCount returns the AchievementCount field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetAchievementCount() int32 {
	if o == nil || o.AchievementCount == nil {
		var ret int32
		return ret
	}
	return *o.AchievementCount
}

// GetAchievementCountOk returns a tuple with the AchievementCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetAchievementCountOk() (*int32, bool) {
	if o == nil || o.AchievementCount == nil {
		return nil, false
	}
	return o.AchievementCount, true
}

// HasAchievementCount returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasAchievementCount() bool {
	if o != nil && o.AchievementCount != nil {
		return true
	}

	return false
}

// SetAchievementCount gets a reference to the given int32 and assigns it to the AchievementCount field.
func (o *SummaryActivityAllOf) SetAchievementCount(v int32) {
	o.AchievementCount = &v
}

// GetKudosCount returns the KudosCount field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetKudosCount() int32 {
	if o == nil || o.KudosCount == nil {
		var ret int32
		return ret
	}
	return *o.KudosCount
}

// GetKudosCountOk returns a tuple with the KudosCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetKudosCountOk() (*int32, bool) {
	if o == nil || o.KudosCount == nil {
		return nil, false
	}
	return o.KudosCount, true
}

// HasKudosCount returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasKudosCount() bool {
	if o != nil && o.KudosCount != nil {
		return true
	}

	return false
}

// SetKudosCount gets a reference to the given int32 and assigns it to the KudosCount field.
func (o *SummaryActivityAllOf) SetKudosCount(v int32) {
	o.KudosCount = &v
}

// GetCommentCount returns the CommentCount field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetCommentCount() int32 {
	if o == nil || o.CommentCount == nil {
		var ret int32
		return ret
	}
	return *o.CommentCount
}

// GetCommentCountOk returns a tuple with the CommentCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetCommentCountOk() (*int32, bool) {
	if o == nil || o.CommentCount == nil {
		return nil, false
	}
	return o.CommentCount, true
}

// HasCommentCount returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasCommentCount() bool {
	if o != nil && o.CommentCount != nil {
		return true
	}

	return false
}

// SetCommentCount gets a reference to the given int32 and assigns it to the CommentCount field.
func (o *SummaryActivityAllOf) SetCommentCount(v int32) {
	o.CommentCount = &v
}

// GetAthleteCount returns the AthleteCount field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetAthleteCount() int32 {
	if o == nil || o.AthleteCount == nil {
		var ret int32
		return ret
	}
	return *o.AthleteCount
}

// GetAthleteCountOk returns a tuple with the AthleteCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetAthleteCountOk() (*int32, bool) {
	if o == nil || o.AthleteCount == nil {
		return nil, false
	}
	return o.AthleteCount, true
}

// HasAthleteCount returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasAthleteCount() bool {
	if o != nil && o.AthleteCount != nil {
		return true
	}

	return false
}

// SetAthleteCount gets a reference to the given int32 and assigns it to the AthleteCount field.
func (o *SummaryActivityAllOf) SetAthleteCount(v int32) {
	o.AthleteCount = &v
}

// GetPhotoCount returns the PhotoCount field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetPhotoCount() int32 {
	if o == nil || o.PhotoCount == nil {
		var ret int32
		return ret
	}
	return *o.PhotoCount
}

// GetPhotoCountOk returns a tuple with the PhotoCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetPhotoCountOk() (*int32, bool) {
	if o == nil || o.PhotoCount == nil {
		return nil, false
	}
	return o.PhotoCount, true
}

// HasPhotoCount returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasPhotoCount() bool {
	if o != nil && o.PhotoCount != nil {
		return true
	}

	return false
}

// SetPhotoCount gets a reference to the given int32 and assigns it to the PhotoCount field.
func (o *SummaryActivityAllOf) SetPhotoCount(v int32) {
	o.PhotoCount = &v
}

// GetTotalPhotoCount returns the TotalPhotoCount field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetTotalPhotoCount() int32 {
	if o == nil || o.TotalPhotoCount == nil {
		var ret int32
		return ret
	}
	return *o.TotalPhotoCount
}

// GetTotalPhotoCountOk returns a tuple with the TotalPhotoCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetTotalPhotoCountOk() (*int32, bool) {
	if o == nil || o.TotalPhotoCount == nil {
		return nil, false
	}
	return o.TotalPhotoCount, true
}

// HasTotalPhotoCount returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasTotalPhotoCount() bool {
	if o != nil && o.TotalPhotoCount != nil {
		return true
	}

	return false
}

// SetTotalPhotoCount gets a reference to the given int32 and assigns it to the TotalPhotoCount field.
func (o *SummaryActivityAllOf) SetTotalPhotoCount(v int32) {
	o.TotalPhotoCount = &v
}

// GetMap returns the Map field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetMap() PolylineMap {
	if o == nil || o.Map == nil {
		var ret PolylineMap
		return ret
	}
	return *o.Map
}

// GetMapOk returns a tuple with the Map field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetMapOk() (*PolylineMap, bool) {
	if o == nil || o.Map == nil {
		return nil, false
	}
	return o.Map, true
}

// HasMap returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasMap() bool {
	if o != nil && o.Map != nil {
		return true
	}

	return false
}

// SetMap gets a reference to the given PolylineMap and assigns it to the Map field.
func (o *SummaryActivityAllOf) SetMap(v PolylineMap) {
	o.Map = &v
}

// GetTrainer returns the Trainer field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetTrainer() bool {
	if o == nil || o.Trainer == nil {
		var ret bool
		return ret
	}
	return *o.Trainer
}

// GetTrainerOk returns a tuple with the Trainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetTrainerOk() (*bool, bool) {
	if o == nil || o.Trainer == nil {
		return nil, false
	}
	return o.Trainer, true
}

// HasTrainer returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasTrainer() bool {
	if o != nil && o.Trainer != nil {
		return true
	}

	return false
}

// SetTrainer gets a reference to the given bool and assigns it to the Trainer field.
func (o *SummaryActivityAllOf) SetTrainer(v bool) {
	o.Trainer = &v
}

// GetCommute returns the Commute field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetCommute() bool {
	if o == nil || o.Commute == nil {
		var ret bool
		return ret
	}
	return *o.Commute
}

// GetCommuteOk returns a tuple with the Commute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetCommuteOk() (*bool, bool) {
	if o == nil || o.Commute == nil {
		return nil, false
	}
	return o.Commute, true
}

// HasCommute returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasCommute() bool {
	if o != nil && o.Commute != nil {
		return true
	}

	return false
}

// SetCommute gets a reference to the given bool and assigns it to the Commute field.
func (o *SummaryActivityAllOf) SetCommute(v bool) {
	o.Commute = &v
}

// GetManual returns the Manual field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetManual() bool {
	if o == nil || o.Manual == nil {
		var ret bool
		return ret
	}
	return *o.Manual
}

// GetManualOk returns a tuple with the Manual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetManualOk() (*bool, bool) {
	if o == nil || o.Manual == nil {
		return nil, false
	}
	return o.Manual, true
}

// HasManual returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasManual() bool {
	if o != nil && o.Manual != nil {
		return true
	}

	return false
}

// SetManual gets a reference to the given bool and assigns it to the Manual field.
func (o *SummaryActivityAllOf) SetManual(v bool) {
	o.Manual = &v
}

// GetPrivate returns the Private field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetPrivate() bool {
	if o == nil || o.Private == nil {
		var ret bool
		return ret
	}
	return *o.Private
}

// GetPrivateOk returns a tuple with the Private field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetPrivateOk() (*bool, bool) {
	if o == nil || o.Private == nil {
		return nil, false
	}
	return o.Private, true
}

// HasPrivate returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasPrivate() bool {
	if o != nil && o.Private != nil {
		return true
	}

	return false
}

// SetPrivate gets a reference to the given bool and assigns it to the Private field.
func (o *SummaryActivityAllOf) SetPrivate(v bool) {
	o.Private = &v
}

// GetFlagged returns the Flagged field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetFlagged() bool {
	if o == nil || o.Flagged == nil {
		var ret bool
		return ret
	}
	return *o.Flagged
}

// GetFlaggedOk returns a tuple with the Flagged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetFlaggedOk() (*bool, bool) {
	if o == nil || o.Flagged == nil {
		return nil, false
	}
	return o.Flagged, true
}

// HasFlagged returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasFlagged() bool {
	if o != nil && o.Flagged != nil {
		return true
	}

	return false
}

// SetFlagged gets a reference to the given bool and assigns it to the Flagged field.
func (o *SummaryActivityAllOf) SetFlagged(v bool) {
	o.Flagged = &v
}

// GetWorkoutType returns the WorkoutType field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetWorkoutType() int32 {
	if o == nil || o.WorkoutType == nil {
		var ret int32
		return ret
	}
	return *o.WorkoutType
}

// GetWorkoutTypeOk returns a tuple with the WorkoutType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetWorkoutTypeOk() (*int32, bool) {
	if o == nil || o.WorkoutType == nil {
		return nil, false
	}
	return o.WorkoutType, true
}

// HasWorkoutType returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasWorkoutType() bool {
	if o != nil && o.WorkoutType != nil {
		return true
	}

	return false
}

// SetWorkoutType gets a reference to the given int32 and assigns it to the WorkoutType field.
func (o *SummaryActivityAllOf) SetWorkoutType(v int32) {
	o.WorkoutType = &v
}

// GetUploadIdStr returns the UploadIdStr field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetUploadIdStr() string {
	if o == nil || o.UploadIdStr == nil {
		var ret string
		return ret
	}
	return *o.UploadIdStr
}

// GetUploadIdStrOk returns a tuple with the UploadIdStr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetUploadIdStrOk() (*string, bool) {
	if o == nil || o.UploadIdStr == nil {
		return nil, false
	}
	return o.UploadIdStr, true
}

// HasUploadIdStr returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasUploadIdStr() bool {
	if o != nil && o.UploadIdStr != nil {
		return true
	}

	return false
}

// SetUploadIdStr gets a reference to the given string and assigns it to the UploadIdStr field.
func (o *SummaryActivityAllOf) SetUploadIdStr(v string) {
	o.UploadIdStr = &v
}

// GetAverageSpeed returns the AverageSpeed field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetAverageSpeed() float32 {
	if o == nil || o.AverageSpeed == nil {
		var ret float32
		return ret
	}
	return *o.AverageSpeed
}

// GetAverageSpeedOk returns a tuple with the AverageSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetAverageSpeedOk() (*float32, bool) {
	if o == nil || o.AverageSpeed == nil {
		return nil, false
	}
	return o.AverageSpeed, true
}

// HasAverageSpeed returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasAverageSpeed() bool {
	if o != nil && o.AverageSpeed != nil {
		return true
	}

	return false
}

// SetAverageSpeed gets a reference to the given float32 and assigns it to the AverageSpeed field.
func (o *SummaryActivityAllOf) SetAverageSpeed(v float32) {
	o.AverageSpeed = &v
}

// GetMaxSpeed returns the MaxSpeed field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetMaxSpeed() float32 {
	if o == nil || o.MaxSpeed == nil {
		var ret float32
		return ret
	}
	return *o.MaxSpeed
}

// GetMaxSpeedOk returns a tuple with the MaxSpeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetMaxSpeedOk() (*float32, bool) {
	if o == nil || o.MaxSpeed == nil {
		return nil, false
	}
	return o.MaxSpeed, true
}

// HasMaxSpeed returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasMaxSpeed() bool {
	if o != nil && o.MaxSpeed != nil {
		return true
	}

	return false
}

// SetMaxSpeed gets a reference to the given float32 and assigns it to the MaxSpeed field.
func (o *SummaryActivityAllOf) SetMaxSpeed(v float32) {
	o.MaxSpeed = &v
}

// GetHasKudoed returns the HasKudoed field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetHasKudoed() bool {
	if o == nil || o.HasKudoed == nil {
		var ret bool
		return ret
	}
	return *o.HasKudoed
}

// GetHasKudoedOk returns a tuple with the HasKudoed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetHasKudoedOk() (*bool, bool) {
	if o == nil || o.HasKudoed == nil {
		return nil, false
	}
	return o.HasKudoed, true
}

// HasHasKudoed returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasHasKudoed() bool {
	if o != nil && o.HasKudoed != nil {
		return true
	}

	return false
}

// SetHasKudoed gets a reference to the given bool and assigns it to the HasKudoed field.
func (o *SummaryActivityAllOf) SetHasKudoed(v bool) {
	o.HasKudoed = &v
}

// GetHideFromHome returns the HideFromHome field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetHideFromHome() bool {
	if o == nil || o.HideFromHome == nil {
		var ret bool
		return ret
	}
	return *o.HideFromHome
}

// GetHideFromHomeOk returns a tuple with the HideFromHome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetHideFromHomeOk() (*bool, bool) {
	if o == nil || o.HideFromHome == nil {
		return nil, false
	}
	return o.HideFromHome, true
}

// HasHideFromHome returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasHideFromHome() bool {
	if o != nil && o.HideFromHome != nil {
		return true
	}

	return false
}

// SetHideFromHome gets a reference to the given bool and assigns it to the HideFromHome field.
func (o *SummaryActivityAllOf) SetHideFromHome(v bool) {
	o.HideFromHome = &v
}

// GetGearId returns the GearId field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetGearId() string {
	if o == nil || o.GearId == nil {
		var ret string
		return ret
	}
	return *o.GearId
}

// GetGearIdOk returns a tuple with the GearId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetGearIdOk() (*string, bool) {
	if o == nil || o.GearId == nil {
		return nil, false
	}
	return o.GearId, true
}

// HasGearId returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasGearId() bool {
	if o != nil && o.GearId != nil {
		return true
	}

	return false
}

// SetGearId gets a reference to the given string and assigns it to the GearId field.
func (o *SummaryActivityAllOf) SetGearId(v string) {
	o.GearId = &v
}

// GetKilojoules returns the Kilojoules field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetKilojoules() float32 {
	if o == nil || o.Kilojoules == nil {
		var ret float32
		return ret
	}
	return *o.Kilojoules
}

// GetKilojoulesOk returns a tuple with the Kilojoules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetKilojoulesOk() (*float32, bool) {
	if o == nil || o.Kilojoules == nil {
		return nil, false
	}
	return o.Kilojoules, true
}

// HasKilojoules returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasKilojoules() bool {
	if o != nil && o.Kilojoules != nil {
		return true
	}

	return false
}

// SetKilojoules gets a reference to the given float32 and assigns it to the Kilojoules field.
func (o *SummaryActivityAllOf) SetKilojoules(v float32) {
	o.Kilojoules = &v
}

// GetAverageWatts returns the AverageWatts field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetAverageWatts() float32 {
	if o == nil || o.AverageWatts == nil {
		var ret float32
		return ret
	}
	return *o.AverageWatts
}

// GetAverageWattsOk returns a tuple with the AverageWatts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetAverageWattsOk() (*float32, bool) {
	if o == nil || o.AverageWatts == nil {
		return nil, false
	}
	return o.AverageWatts, true
}

// HasAverageWatts returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasAverageWatts() bool {
	if o != nil && o.AverageWatts != nil {
		return true
	}

	return false
}

// SetAverageWatts gets a reference to the given float32 and assigns it to the AverageWatts field.
func (o *SummaryActivityAllOf) SetAverageWatts(v float32) {
	o.AverageWatts = &v
}

// GetDeviceWatts returns the DeviceWatts field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetDeviceWatts() bool {
	if o == nil || o.DeviceWatts == nil {
		var ret bool
		return ret
	}
	return *o.DeviceWatts
}

// GetDeviceWattsOk returns a tuple with the DeviceWatts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetDeviceWattsOk() (*bool, bool) {
	if o == nil || o.DeviceWatts == nil {
		return nil, false
	}
	return o.DeviceWatts, true
}

// HasDeviceWatts returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasDeviceWatts() bool {
	if o != nil && o.DeviceWatts != nil {
		return true
	}

	return false
}

// SetDeviceWatts gets a reference to the given bool and assigns it to the DeviceWatts field.
func (o *SummaryActivityAllOf) SetDeviceWatts(v bool) {
	o.DeviceWatts = &v
}

// GetMaxWatts returns the MaxWatts field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetMaxWatts() int32 {
	if o == nil || o.MaxWatts == nil {
		var ret int32
		return ret
	}
	return *o.MaxWatts
}

// GetMaxWattsOk returns a tuple with the MaxWatts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetMaxWattsOk() (*int32, bool) {
	if o == nil || o.MaxWatts == nil {
		return nil, false
	}
	return o.MaxWatts, true
}

// HasMaxWatts returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasMaxWatts() bool {
	if o != nil && o.MaxWatts != nil {
		return true
	}

	return false
}

// SetMaxWatts gets a reference to the given int32 and assigns it to the MaxWatts field.
func (o *SummaryActivityAllOf) SetMaxWatts(v int32) {
	o.MaxWatts = &v
}

// GetWeightedAverageWatts returns the WeightedAverageWatts field value if set, zero value otherwise.
func (o *SummaryActivityAllOf) GetWeightedAverageWatts() int32 {
	if o == nil || o.WeightedAverageWatts == nil {
		var ret int32
		return ret
	}
	return *o.WeightedAverageWatts
}

// GetWeightedAverageWattsOk returns a tuple with the WeightedAverageWatts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryActivityAllOf) GetWeightedAverageWattsOk() (*int32, bool) {
	if o == nil || o.WeightedAverageWatts == nil {
		return nil, false
	}
	return o.WeightedAverageWatts, true
}

// HasWeightedAverageWatts returns a boolean if a field has been set.
func (o *SummaryActivityAllOf) HasWeightedAverageWatts() bool {
	if o != nil && o.WeightedAverageWatts != nil {
		return true
	}

	return false
}

// SetWeightedAverageWatts gets a reference to the given int32 and assigns it to the WeightedAverageWatts field.
func (o *SummaryActivityAllOf) SetWeightedAverageWatts(v int32) {
	o.WeightedAverageWatts = &v
}

func (o SummaryActivityAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ExternalId != nil {
		toSerialize["external_id"] = o.ExternalId
	}
	if o.UploadId != nil {
		toSerialize["upload_id"] = o.UploadId
	}
	if o.Athlete != nil {
		toSerialize["athlete"] = o.Athlete
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Distance != nil {
		toSerialize["distance"] = o.Distance
	}
	if o.MovingTime != nil {
		toSerialize["moving_time"] = o.MovingTime
	}
	if o.ElapsedTime != nil {
		toSerialize["elapsed_time"] = o.ElapsedTime
	}
	if o.TotalElevationGain != nil {
		toSerialize["total_elevation_gain"] = o.TotalElevationGain
	}
	if o.ElevHigh != nil {
		toSerialize["elev_high"] = o.ElevHigh
	}
	if o.ElevLow != nil {
		toSerialize["elev_low"] = o.ElevLow
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.SportType != nil {
		toSerialize["sport_type"] = o.SportType
	}
	if o.StartDate != nil {
		toSerialize["start_date"] = o.StartDate
	}
	if o.StartDateLocal != nil {
		toSerialize["start_date_local"] = o.StartDateLocal
	}
	if o.Timezone != nil {
		toSerialize["timezone"] = o.Timezone
	}
	if o.StartLatlng != nil {
		toSerialize["start_latlng"] = o.StartLatlng
	}
	if o.EndLatlng != nil {
		toSerialize["end_latlng"] = o.EndLatlng
	}
	if o.AchievementCount != nil {
		toSerialize["achievement_count"] = o.AchievementCount
	}
	if o.KudosCount != nil {
		toSerialize["kudos_count"] = o.KudosCount
	}
	if o.CommentCount != nil {
		toSerialize["comment_count"] = o.CommentCount
	}
	if o.AthleteCount != nil {
		toSerialize["athlete_count"] = o.AthleteCount
	}
	if o.PhotoCount != nil {
		toSerialize["photo_count"] = o.PhotoCount
	}
	if o.TotalPhotoCount != nil {
		toSerialize["total_photo_count"] = o.TotalPhotoCount
	}
	if o.Map != nil {
		toSerialize["map"] = o.Map
	}
	if o.Trainer != nil {
		toSerialize["trainer"] = o.Trainer
	}
	if o.Commute != nil {
		toSerialize["commute"] = o.Commute
	}
	if o.Manual != nil {
		toSerialize["manual"] = o.Manual
	}
	if o.Private != nil {
		toSerialize["private"] = o.Private
	}
	if o.Flagged != nil {
		toSerialize["flagged"] = o.Flagged
	}
	if o.WorkoutType != nil {
		toSerialize["workout_type"] = o.WorkoutType
	}
	if o.UploadIdStr != nil {
		toSerialize["upload_id_str"] = o.UploadIdStr
	}
	if o.AverageSpeed != nil {
		toSerialize["average_speed"] = o.AverageSpeed
	}
	if o.MaxSpeed != nil {
		toSerialize["max_speed"] = o.MaxSpeed
	}
	if o.HasKudoed != nil {
		toSerialize["has_kudoed"] = o.HasKudoed
	}
	if o.HideFromHome != nil {
		toSerialize["hide_from_home"] = o.HideFromHome
	}
	if o.GearId != nil {
		toSerialize["gear_id"] = o.GearId
	}
	if o.Kilojoules != nil {
		toSerialize["kilojoules"] = o.Kilojoules
	}
	if o.AverageWatts != nil {
		toSerialize["average_watts"] = o.AverageWatts
	}
	if o.DeviceWatts != nil {
		toSerialize["device_watts"] = o.DeviceWatts
	}
	if o.MaxWatts != nil {
		toSerialize["max_watts"] = o.MaxWatts
	}
	if o.WeightedAverageWatts != nil {
		toSerialize["weighted_average_watts"] = o.WeightedAverageWatts
	}
	return json.Marshal(toSerialize)
}

type NullableSummaryActivityAllOf struct {
	value *SummaryActivityAllOf
	isSet bool
}

func (v NullableSummaryActivityAllOf) Get() *SummaryActivityAllOf {
	return v.value
}

func (v *NullableSummaryActivityAllOf) Set(val *SummaryActivityAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSummaryActivityAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSummaryActivityAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummaryActivityAllOf(val *SummaryActivityAllOf) *NullableSummaryActivityAllOf {
	return &NullableSummaryActivityAllOf{value: val, isSet: true}
}

func (v NullableSummaryActivityAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummaryActivityAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


