/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package strava
// DetailedClubAllOf struct for DetailedClubAllOf
type DetailedClubAllOf struct {
	// The membership status of the logged-in athlete.
	Membership string `json:"membership,omitempty"`
	// Whether the currently logged-in athlete is an administrator of this club.
	Admin bool `json:"admin,omitempty"`
	// Whether the currently logged-in athlete is the owner of this club.
	Owner bool `json:"owner,omitempty"`
	// The number of athletes in the club that the logged-in athlete follows.
	FollowingCount int32 `json:"following_count,omitempty"`
}
