/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * API version: 3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package strava
// DetailedActivityAllOf struct for DetailedActivityAllOf
type DetailedActivityAllOf struct {
	// The description of the activity
	Description string `json:"description,omitempty"`
	Photos PhotosSummary `json:"photos,omitempty"`
	Gear SummaryGear `json:"gear,omitempty"`
	// The number of kilocalories consumed during this activity
	Calories float32 `json:"calories,omitempty"`
	SegmentEfforts []DetailedSegmentEffort `json:"segment_efforts,omitempty"`
	// The name of the device used to record the activity
	DeviceName string `json:"device_name,omitempty"`
	// The token used to embed a Strava activity
	EmbedToken string `json:"embed_token,omitempty"`
	// The splits of this activity in metric units (for runs)
	SplitsMetric []Split `json:"splits_metric,omitempty"`
	// The splits of this activity in imperial units (for runs)
	SplitsStandard []Split `json:"splits_standard,omitempty"`
	Laps []Lap `json:"laps,omitempty"`
	BestEfforts []DetailedSegmentEffort `json:"best_efforts,omitempty"`
}
